# encoding: utf-8
development:
  adapter: mysql2
  encoding: utf8
  database: carrier_app
  pool: 5
  username: root
  password: 'helloworld91@'
test:
  adapter: mysql2
  encoding: utf8
  database: carrier_app_test
  pool: 5
  username: root
  password: 'helloworld91@'
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: carrier_app_pr
  pool: 5
  username: root
  password: "helloworld91@"
